### ISSUE TITLE
findOneAndUpdate vs findAndModify

### ISSUE THREAD

**Issue by jsainzvela** [chilts/mongodb-queue#13]
Hi,

just a clarification. I see you claim to use the findAndModify operation as the basis of the .get() method of your module, but when I dig into the code I just see the following line:

`self.col.findOneAndUpdate(query, update, { sort: sort, returnOriginal : false }, function(err, result)`

Are those the same operations internally? They are supposed to be different:

https://docs.mongodb.com/manual/reference/command/findAndModify/
https://docs.mongodb.com/manual/reference/method/db.collection.findOneAndUpdate/

Thanks a lot in advance!

Jorge

**Comment by chilts** [comment]
Oh right, ok, I'll look into it and see what the difference is and whether I should be using the other. :) Many thanks for pointing it out!

**Comment by jsainzvela** [comment]
Not a prob Andrew, we are just developing something similar (in both
Pyton and Perl) and run into the same problem, so I was looking for a
"reference implementation".

Thanks!

Jorge

**Comment by chilts** [comment]
I think the code is new functions from the 3.x MongoDB series such as `findOneAndUpdate`, and the `findAndUpdate` is deprecated. There was a PR with this information in here from @hanwencheng:

* https://github.com/chilts/mongodb-queue/commit/aad6b70b6b6f3133019aa0dca3d37761a855cbb0

So yeah, I think the docs are wrong there. I'll update them (or in fact, probably remove it and just say it's atomic, so we don't get conflicting info again). :)

Thanks for raising this and sorry it's taken me so long to look into it!

**Comment by jsainzvela** [comment]
No prob @chilts, thanks to you!

**Comment by chilts** [comment]
I'll just leave open to remind me to do the docs. :) Thanks.

**Comment by chilts** [comment]
v4.0.0 was released around 7 months ago and now uses MongoDB v3 driver and should be all up to date now.
