### ISSUE TITLE
Error acknowledging a queue: Queue.ack(): Unidentified ack

### ISSUE THREAD

**Issue by jhon-andrew** [chilts/mongodb-queue#44]
When acknowledging a queue, I am getting this error:

```
Queue.ack(): Unidentified ack : 735fae706d31ca7e0488377735c75e4d
```

What is causing this error and how can I avoid it?

**Comment by sadortun** [comment]
Is it possible that you already ack the same message twice ? 

After the error, you can check the queue collection and check if either this ack ID is missing from the table, or `delete` is non null.

**Comment by jhon-andrew** [comment]
> Is it possible that you already ack the same message twice ?
> 
> After the error, you can check the queue collection and check if either this ack ID is missing from the table, or `delete` is non null.

Thank you for your response. I don't think that's the case because the first task I get is the one that returns that error.

But I have seem to manage and fix the issue already. It looks like the task performed after getting a queue took very long and it was already put back to queue before I acknowledge it is done.

Extending the `visibility` fixed the issue.

Thanks!

**Comment by sadortun** [comment]
Awesome!
