### ISSUE TITLE
Support MongoDB 3.x

### ISSUE THREAD

**Issue by nicekiwi** [chilts/mongodb-queue#7]

**Comment by chilts** [comment]
Specifically, what features are you wanting from 3.x for the project?

Thanks.

**Comment by coderofsalvation** [comment]
@nicekiwi are you referring to https://github.com/chilts/mongodb-queue/issues/24 ?

**Comment by chilts** [comment]
I think this is all done now as of v4.0.0 released about 7 months ago. :)
